"""The notebooks are the user-facing entry point, so guard them like code.

They are generated by ``scripts/build_notebooks.py``. These tests check that the
generated files are valid, that every script they invoke exists, and that the
GitHub URL placeholder was replaced before the repo was published.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_DIR = REPO_ROOT / "notebooks"
NOTEBOOKS = sorted(NOTEBOOK_DIR.glob("*.ipynb"))

SHELL_PREFIXES = ("!", "%")
SCRIPT_PATTERN = re.compile(r"scripts/([A-Za-z0-9_]+\.py)")


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def cell_source(cell: dict) -> str:
    return "".join(cell["source"])


def strip_shell_magics(source: str) -> str:
    """Replace IPython shell lines with ``pass``, keeping indentation.

    A ``!command`` may span several lines via trailing backslashes; the whole
    run collapses to a single statement so that a magic inside an ``if`` block
    still leaves a syntactically valid body.
    """
    lines = source.split("\n")
    output: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        if line.lstrip().startswith(SHELL_PREFIXES):
            indent = line[: len(line) - len(line.lstrip())]
            output.append(indent + "pass")
            while index < len(lines) - 1 and lines[index].rstrip().endswith("\\"):
                index += 1
        else:
            output.append(line)
        index += 1
    return "\n".join(output)


def test_notebooks_exist():
    assert NOTEBOOKS, f"No notebooks found under {NOTEBOOK_DIR}"


@pytest.mark.parametrize("path", NOTEBOOKS, ids=lambda p: p.name)
def test_notebook_is_valid_nbformat(path: Path):
    notebook = load(path)
    assert notebook["nbformat"] == 4
    assert notebook["cells"], "notebook has no cells"
    for cell in notebook["cells"]:
        assert cell["cell_type"] in {"code", "markdown"}
        assert isinstance(cell["source"], list)


@pytest.mark.parametrize("path", NOTEBOOKS, ids=lambda p: p.name)
def test_code_cells_are_syntactically_valid(path: Path):
    """A typo in a notebook cell is only discovered halfway through a GPU session."""
    notebook = load(path)
    for index, cell in enumerate(notebook["cells"]):
        if cell["cell_type"] != "code":
            continue
        body = strip_shell_magics(cell_source(cell))
        try:
            compile(body, f"{path.name}#cell{index}", "exec")
        except SyntaxError as error:
            pytest.fail(f"{path.name} cell {index}: {error}")


@pytest.mark.parametrize("path", NOTEBOOKS, ids=lambda p: p.name)
def test_referenced_scripts_exist(path: Path):
    """Catches a renamed script before a user hits it on Kaggle."""
    referenced = set()
    for cell in load(path)["cells"]:
        referenced.update(SCRIPT_PATTERN.findall(cell_source(cell)))

    missing = [name for name in sorted(referenced) if not (REPO_ROOT / "scripts" / name).exists()]
    assert not missing, f"{path.name} calls missing script(s): {missing}"


@pytest.mark.parametrize("path", NOTEBOOKS, ids=lambda p: p.name)
def test_no_unreplaced_repo_placeholder(path: Path):
    """The clone cell must point at a real repository, not the template value."""
    text = path.read_text(encoding="utf-8")
    assert "REPLACE-ME" not in text, (
        f"{path.name} still contains the REPO_URL placeholder. "
        "Set REPO_URL in scripts/build_notebooks.py and re-run it."
    )


@pytest.mark.parametrize("path", NOTEBOOKS, ids=lambda p: p.name)
def test_notebook_opens_with_a_title(path: Path):
    first = load(path)["cells"][0]
    assert first["cell_type"] == "markdown"
    assert cell_source(first).lstrip().startswith("#")


def test_generator_reproduces_the_committed_notebooks(tmp_path, monkeypatch):
    """The .ipynb files must be regenerable, so edits go to the generator.

    If this fails, someone edited a notebook by hand and the change would be
    silently lost the next time build_notebooks.py runs.
    """
    import sys

    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import build_notebooks

    monkeypatch.setattr(build_notebooks, "NOTEBOOK_DIR", tmp_path)
    build_notebooks.main()

    for committed in NOTEBOOKS:
        regenerated = tmp_path / committed.name
        assert regenerated.exists(), f"{committed.name} is not produced by the generator"
        assert json.loads(regenerated.read_text(encoding="utf-8")) == load(committed), (
            f"{committed.name} differs from what build_notebooks.py generates -- "
            "edit the generator, then re-run it."
        )
